### ISSUE TITLE
Oscar and SageMath via PyCall

### ISSUE THREAD

**Issue by mbuze** [oscar-system/Oscar.jl#3162]
**Describe the bug**
Loading Oscar after SageMath results in a segmentation fault. Loading SageMath after Oscar results in an error. 

**To Reproduce**
```
# install and load SageMath via PyCall
using Conda
Conda.add("sagelib")
using PyCall
sage = pyimport("sage")
sage = pyimport("sage.all") 
sage = pyimport("sage.all") # due to a know bug, the first execution results in an error, but the second run does not
C = sage.polytopes.cube() # example command to check if SageMath works

#load Oscar
using Oscar
```
This results in a segmentation fault:
```
------------------------------------------------------------------------
/home/mb/.julia/conda/3/lib/python3.10/site-packages/cysignals/signals.cpython-310-x86_64-linux-gnu.so(+0x6f4d)[0x7f289eb86f4d]
/home/mb/.julia/conda/3/lib/python3.10/site-packages/cysignals/signals.cpython-310-x86_64-linux-gnu.so(+0x714c)[0x7f289eb8714c]
/home/mb/.julia/conda/3/lib/python3.10/site-packages/cysignals/signals.cpython-310-x86_64-linux-gnu.so(+0x972c)[0x7f289eb8972c]
/lib64/libc.so.6(+0x3cb60)[0x7f28b7a50b60]
/home/mb/.julia/artifacts/a4813357741f4b3b82df69428c9c158bd314604a/lib/libgap.so(+0x13eb39)[0x7f27ca93eb39]
/home/mb/.julia/artifacts/a4813357741f4b3b82df69428c9c158bd314604a/lib/libgap.so(+0x13fd37)[0x7f27ca93fd37]
/home/mb/.julia/juliaup/julia-1.9.3/bin/../lib/julia/libjulia-internal.so.1(+0x9a524)[0x7f28b6c9a524]
/home/mb/.julia/juliaup/julia-1.9.3/bin/../lib/julia/libjulia-internal.so.1(+0x9cb0e)[0x7f28b6c9cb0e]
/home/mb/.julia/juliaup/julia-1.9.3/bin/../lib/julia/libjulia-internal.so.1(ijl_gc_collect+0x28b)[0x7f28b6c9e5eb]
/home/mb/.julia/compiled/v1.9/GAP/YqHod_XKUor.so(+0x1ca9d)[0x7f27ca41ca9d]
------------------------------------------------------------------------
Attaching gdb to process id 35472.
GNU gdb (GDB) Fedora Linux 13.2-3.fc37
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
[New LWP 35474]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.fedoraproject.org/>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f28b7aea5f7 in wait4 () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install Singular-libs-4.2.1p3-3.fc37.x86_64 glibc-2.36-18.fc37.x86_64 mathic-1.0-24.20220426.git18ff8de.fc37.x86_64 mathicgb-libs-1.0-31.20220621.gitf3a05da.fc37.x86_64 memtailor-1.0-20.20220104.git95dbac7.fc37.x86_64 tbb-2020.3-13.fc37.x86_64

Stack backtrace
---------------
No symbol table info available.
#1  0x00007f289eb87011 in print_enhanced_backtrace () at build/src/cysignals/implementation.c:586
        parent_pid = 35472
        pid = <optimized out>
#2  0x00007f289eb8718b in sigdie (sig=sig@entry=11, s=s@entry=0x7f289eb8fb48 "Unhandled SIGSEGV: A segmentation fault occurred.")
    at build/src/cysignals/implementation.c:612
No locals.
#3  0x00007f289eb8972c in sigdie_for_sig (inside=0, sig=11) at build/src/cysignals/implementation.c:179
No locals.
#4  cysigs_signal_handler (sig=11) at build/src/cysignals/implementation.c:278
        inside = <optimized out>
#5  <signal handler called>
No symbol table info available.
#6  FindLiveRangeReverse (end=0x7f2884400000, start=<optimized out>, arr=0xe96ba40) at src/julia_gc.c:424
        addr = <optimized out>
        p = <optimized out>
        q = 0x7f2884007ffe ""
        p = <optimized out>
        q = <optimized out>
        SWAP_TMP = <optimized out>
        addr = <optimized out>
#7  SafeScanTaskStack (stack=stack@entry=0xe96ba40, start=start@entry=0x7f2884000000, end=end@entry=0x7f2884400000)
    at src/julia_gc.c:497
        old_safe_restore = 0x0
        exc_buf = {{__jmpbuf = {1, -971812645882529772, 139811990011904, 139811994206208, 139812451371376, 249241760, 
              972558974703400980, 922364389623625748}, __mask_was_saved = 0, __saved_mask = {__val = {139808879146371, 
                139812858133632, 139812451371376, 244759104, 139812451371376, 249241760, 139812856849687, 246920416, 8192, 
                2314885530279477355, 249241776, 0, 8192, 139812858133632, 18446744073709551536, 139811994206208}}}}
#8  0x00007f27ca93fd37 in ScanTaskStack (end=<optimized out>, start=0x7f2884000000, task=0x7f289f7fc970, rescan=1)
    at src/julia_gc.c:523
        tmp = <optimized out>
        taskinfo = <optimized out>
        stack = 0xe96ba40
        tmp = <optimized out>
        taskinfo = <optimized out>
        stack = <optimized out>
        p = <optimized out>
        i = <optimized out>
#9  GapTaskScanner (task=0x7f289f7fc970, root_task=<optimized out>) at src/julia_gc.c:665
        rescan = 1
        active_start = 0x7f2884000000 ""
        active_end = 0x7f2884400000 ""
        total_start = 0x7f2884000000 ""
        total_end = 0x7f2884400000 ""
#10 0x00007f28b6c9a524 in gc_mark_loop (ptls=ptls@entry=0x245e740, sp=...)
    at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gc.c:2955
        cb = 0xd794b20
        tid = <optimized out>
        nroots = <optimized out>
        offset = <optimized out>
        layout = <optimized out>
        stkbuf = <optimized out>
        ub = <optimized out>
        nptr = <optimized out>
        ta = <optimized out>
        s = <optimized out>
        lb = <optimized out>
        npointers = <optimized out>
        markdata = {parent = 0x7f289a497cb0 <jl_system_image_data+74488240>, 
          begin = 0x7f289a497cb8 <jl_system_image_data+74488248> " )K\232(\177", 
          end = 0x7f289a498308 <jl_system_image_data+74489864> "\307\304\361\232(\177", nptr = 1}
        o = <optimized out>
        vt = <optimized out>
        foreign_alloc = <optimized out>
        update_meta = <optimized out>
        new_obj = <optimized out>
        tag = 139812374946560
        bits = 3 '\003'
        meta_updated = 0
        objary = <optimized out>
        objary_begin = <optimized out>
        objary_end = <optimized out>
        ary8 = <optimized out>
        ary16 = <optimized out>
        obj8 = <optimized out>
        obj8_parent = <optimized out>
        obj8_begin = <optimized out>
        obj8_end = <optimized out>
        obj16 = <optimized out>
        obj16_parent = <optimized out>
        obj16_begin = <optimized out>
        obj16_end = <optimized out>
        pop = <optimized out>
        mark = <optimized out>
        objarray_loaded = <optimized out>
        array8_loaded = <optimized out>
        array16_loaded = <optimized out>
        obj8_loaded = <optimized out>
        obj16_loaded = <optimized out>
#11 0x00007f28b6c9cb0e in _jl_gc_collect (ptls=ptls@entry=0x245e740, collection=collection@entry=JL_GC_FULL)
    at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gc.c:3407
        gc_cache = 0x24603a8
        sp = {pc = 0x7f2882dfdf50, data = 0x7f2883000dd0, pc_start = 0x7f2882dfd010, pc_end = 0x7f2882ffd010}
        gc_start_time = <optimized out>
        last_perm_scanned_bytes = <optimized out>
        start_mark_time = <optimized out>
        end_mark_time = <optimized out>
        mark_time = <optimized out>
        actual_allocd = <optimized out>
        orig_marked_len = <optimized out>
        live_sz_ub = <optimized out>
        live_sz_est = <optimized out>
        estimate_freed = <optimized out>
        not_freed_enough = <optimized out>
        nptr = <optimized out>
        large_frontier = <optimized out>
        sweep_full = <optimized out>
        recollect = <optimized out>
        start_sweep_time = <optimized out>
        gc_end_time = <optimized out>
        pause = <optimized out>
        sweep_time = <optimized out>
        max_memory = <optimized out>
#12 0x00007f28b6c9e5eb in ijl_gc_collect (collection=JL_GC_FULL)
    at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gc.c:3713
        ct = 0x7f289f7fc010
        ptls = 0x245e740
        old_state = 0 '\000'
        t0 = <optimized out>
        last_errno = 2
        t1 = <optimized out>
        duration = <optimized out>
#13 0x00007f27ca41ca9d in gc () at gcutils.jl:98
No locals.
#14 julia_initialize_530 () at /home/mb/.julia/packages/GAP/gliHT/src/GAP.jl:135
No locals.
#15 0x00007f289377312d in ?? ()
No symbol table info available.
#16 0x00007f282198a0e0 in ?? ()
No symbol table info available.
#17 0x00007f28a38071a0 in ?? ()
No symbol table info available.
#18 0x00007f28a3807120 in ?? ()
No symbol table info available.
#19 0x00007f289f7fc078 in ?? ()
No symbol table info available.
#20 0x0000000000000020 in ?? ()
No symbol table info available.
#21 0x00007ffe24ceab60 in ?? ()
No symbol table info available.
#22 0x0000000000000000 in ?? ()
No symbol table info available.


Cython backtrace
----------------
#0  0x00007f28b7aea5a0 in wait4 ()
#1  0x00007f289eb86fb0 in print_enhanced_backtrace () at /usr/local/src/conda/cysignals-1.11.2/build/src/cysignals/implementation.c:586
#2  0x00007f289eb87110 in sigdie () at /usr/local/src/conda/cysignals-1.11.2/build/src/cysignals/implementation.c:612
#3  0x00007f289eb894be in sigdie_for_sig () at /usr/local/src/conda/cysignals-1.11.2/build/src/cysignals/implementation.c:179
#4  0x00007f289eb894a0 in cysigs_signal_handler () at /usr/local/src/conda/cysignals-1.11.2/build/src/cysignals/implementation.c:278
#5  0x00007f28b7c34f90 in __restore_rt ()
#6  0x00007f27ca93eafa in FindLiveRangeReverse () at /workspace/srcdir/gap-4.12.2/src/julia_gc.c:424
#7  0x00007f27ca93ea90 in SafeScanTaskStack () at /workspace/srcdir/gap-4.12.2/src/julia_gc.c:497
#8  0x00007f27ca93fc1e in ScanTaskStack () at /workspace/srcdir/gap-4.12.2/src/julia_gc.c:523
#9  0x00007f27ca93fbb0 in GapTaskScanner () at /workspace/srcdir/gap-4.12.2/src/julia_gc.c:665
#10 0x00007f28b6c97330 in gc_mark_loop () at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gc.c:2955
#11 0x00007f28b6c9c550 in _jl_gc_collect () at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gc.c:3407
#12 0x00007f28b6c9e360 in ijl_gc_collect () at /cache/build/default-amdci5-5/julialang/julia-release-1-dot-9/src/gc.c:3713
#13 0x00007f27ca41ca92 in gc () at ./gcutils.jl:98
#14 0x00007f27ca41c7a0 in julia_initialize_530 () at /home/mb/.julia/packages/GAP/gliHT/src/GAP.jl:135
   130            error_handler_func,
   131            handle_signals,
   132        )
   133    
   134        # HACK HACK HACK workaround
>  135        Base.GC.gc(true)
   136    
   137        ## At this point, the GAP module has not been completely initialized, and
   138        ## hence is not yet available under the global binding "GAP"; but
   139        ## JuliaInterface needs to access it. To make that possible, we dlopen
#15 0x0000000000000000 in ?? ()
#16 0x0000000000000000 in ?? ()
#17 0x0000000000000000 in ?? ()
#18 0x0000000000000000 in ?? ()
#19 0x0000000000000000 in ?? ()
#20 0x0000000000000000 in ?? ()
#21 0x0000000000000000 in ?? ()
#22 0x0000000000000000 in ?? ()

[Inferior 1 (process 35472) detached]
Saved trace to ...
------------------------------------------------------------------------
Unhandled SIGSEGV: A segmentation fault occurred.
This probably occurred because a *compiled* module has a bug
in it and is not properly wrapped with sig_on(), sig_off().
Python will now terminate.
------------------------------------------------------------------------
Segmentation fault (core dumped)
```

**Expected behavior**
Either that we can use Oscar and SageMath side by side, or that trying to load Oscar after SageMath results in an error and not in a segmentation fault which results in Julia REPL being exited without warning. 

**System:**
```
julia> Oscar.versioninfo(full=true)
OSCAR version 0.13.0
  combining:
    AbstractAlgebra.jl   v0.31.1
    GAP.jl               v0.9.8
    Hecke.jl             v0.20.3
    Nemo.jl              v0.35.3
    Polymake.jl          v0.11.10
    Singular.jl          v0.18.16
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.7+0
    GAP_jll                 v400.1200.200+7
    Singular_jll            v403.208.800+0
    libpolymake_julia_jll   v0.11.2+0
    libsingular_julia_jll   v0.40.3+0
    polymake_jll            v400.1100.1+0
See `]st -m` for a full list of dependencies.

Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 4 virtual cores
Official https://julialang.org/ release
...
```
**Additional context**
The environment is
```
(@v1.9) pkg> status
Status `~/.julia/environments/v1.9/Project.toml`
  [8f4d0f93] Conda v1.10.0
  [b964fa9f] LaTeXStrings v1.3.1
  [f1435218] Oscar v0.13.0
  [c3e4b0f8] Pluto v0.19.36
  [438e738f] PyCall v1.96.4
  [770da0de] UpdateJulia v0.4.4
```

If we load Oscar first and then try to load SageMath:
```
using Oscar
using Conda
Conda.add("sagelib")
using PyCall
sage = pyimport("sage")
sage = pyimport("sage.all")
```
then we get the error
```
ERROR: PyError (PyImport_ImportModule) <class 'TypeError'>
TypeError('signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object')
  File "/home/mb/.julia/conda/3/lib/python3.10/site-packages/sage/all.py", line 130, in <module>
    from sage.libs.all       import *
  File "/home/mb/.julia/conda/3/lib/python3.10/site-packages/sage/libs/all.py", line 2, in <module>
    import sage.libs.ntl.all as ntl
  File "/home/mb/.julia/conda/3/lib/python3.10/site-packages/sage/libs/ntl/all.py", line 50, in <module>
    from sage.libs.ntl.ntl_lzz_p import ntl_zz_p as zz_p
  File "sage/libs/ntl/ntl_lzz_p.pyx", line 1, in init sage.libs.ntl.ntl_lzz_p (build/cythonized/sage/libs/ntl/ntl_lzz_p.cpp:10032)
    # distutils: libraries = NTL_LIBRARIES gmp m
  File "sage/rings/finite_rings/integer_mod.pyx", line 94, in init sage.rings.finite_rings.integer_mod (build/cythonized/sage/rings/finite_rings/integer_mod.c:50644)
    import sage.interfaces.all
  File "/home/mb/.julia/conda/3/lib/python3.10/site-packages/sage/interfaces/all.py", line 7, in <module>
    from .axiom import Axiom, axiom
  File "/home/mb/.julia/conda/3/lib/python3.10/site-packages/sage/interfaces/axiom.py", line 182, in <module>
    from .expect import Expect, ExpectElement, FunctionElement, ExpectFunction
  File "/home/mb/.julia/conda/3/lib/python3.10/site-packages/sage/interfaces/expect.py", line 55, in <module>
    from sage.interfaces.sagespawn import SageSpawn
  File "sage/interfaces/sagespawn.pyx", line 1, in init sage.interfaces.sagespawn (build/cythonized/sage/interfaces/sagespawn.c:5481)
    """
  File "sage/interfaces/process.pyx", line 24, in init sage.interfaces.process (build/cythonized/sage/interfaces/process.c:5483)
    from cysignals.pysignals import changesignal
  File "src/cysignals/pysignals.pyx", line 486, in init cysignals.pysignals
  File "src/cysignals/pysignals.pyx", line 370, in cysignals.pysignals.changesignal.__exit__
  File "src/cysignals/pysignals.pyx", line 316, in cysignals.pysignals.setsignal
  File "/home/mb/.julia/conda/3/lib/python3.10/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))

Stacktrace:
 [1] pyimport(name::String)
   @ PyCall ~/.julia/packages/PyCall/1gn3u/src/PyCall.jl:558
 [2] top-level scope
   @ REPL[13]:1
```
This error is also present when we first try to load SageMath as explained above, but the difference is that without Oscar loaded, the second try succeeds and SageMath is loaded successfully, whereas now this error persists for ever.

**Comment by fingolfin** [comment]
This is basically impossible to resolve, at least not from our side, and with everything in one process: both Oscar and Sage are accessing GAP via libgap. But they use *different* versions of libgap: Oscar uses a libgap built against the Julia garbage collector, while Sage uses a libgap built against the classic GAP garbage collector (called "GASMAN"). These two have different ABIs. One would have to recompile parts of Sage (written in Cython) against the Julia libgap, at the very least.

But there is much more overlap, i.e, both projects use GMP, MPFR, FLINT, etc. -- in each case it's a roll of dice if the two versions are binary compatible by chance or not... Plus we / Julia register function callbacks with some of these (e.g. to control memory management), this will likely also cause severe issues (I have not checked that, but it's a reasonable guess).

All in all I don't see a way to make this work with reasonable effort.
