### ISSUE TITLE
Test failures, possible caused by GAP.jl 0.7.1

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#774]
Seeing these failures [in ci](https://github.com/oscar-system/Oscar.jl/runs/4047784113?check_suite_focus=true) for PR #744 (which is just modifying docs, so shouldn't affect regular tests at all):
```
Test Summary:              | Pass  Total
Other automorphisms groups |    2      2
Test Summary: | Pass  Total
Transitivity  |   22     22
ERROR: Package Oscar errored during testing (received signal: KILL)
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:55
 [2] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing)
   @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1693
 [3] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Symbol, IOContext{Base.PipeEndpoint}, Tuple{Symbol}, NamedTuple{(:io,), Tuple{IOContext{Base.PipeEndpoint}}}})
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:343
 [4] test(pkgs::Vector{Pkg.Types.PackageSpec}; io::IOContext{Base.PipeEndpoint}, kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:coverage,), Tuple{Bool}}})
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:80
 [5] test(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:coverage,), Tuple{Bool}}})
   @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:96
 [6] top-level scope
   @ none:1
Error: Process completed with exit code 1.
Run doctests
```

I am suspecting this is caused by GAP.jl 0.7.1 :-(. I have absolutely no idea *how* at this point, but I'll look at it. However, I have to head home now. I am posting this here so people know what's going on. 

Any ideas welcome. I'll try to fix this tonight, at worst gotta yank that version :-(

**Comment by tthsqe12** [comment]
I get this locally
```
Test Summary:       | Pass  Total
Kernel and cokernel |   58     58
Test Summary:                | Pass  Total
Automorphism group of Sym(n) |   33     33
Test Summary:              | Pass  Total
Other automorphisms groups |    2      2
Test Summary: | Pass  Total
Transitivity  |   22     22
ERROR: Package Oscar errored during testing (received signal: KILL)
```

**Comment by benlorenz** [comment]
I was just looking into this before I saw your post, I can reproduce this locally as well. It seems to be allocating excessive amounts of memory, attaching gdb while the process was at about 60GB gave:
```
(gdb) bt
#0  0x000014b5415c013d in __memset_avx2_erms () from /lib64/libc.so.6
#1  0x000014b4aaa8de06 in AllocateBagMemory (type=type@entry=72, size=size@entry=20163720699) at src/julia_gc.c:301
#2  0x000014b4aaa8f811 in NewBag (type=type@entry=72, size=size@entry=20163720691) at src/julia_gc.c:1093
#3  0x000014b4aaa55071 in NEW_STRING (len=len@entry=20163720682) at src/stringobj.c:420
#4  0x000014b4aaa04c4d in FuncMULT_BYT_LETTREP (self=<optimized out>, a=0x14b450020200, b=0x14b450020180) at src/objfgelm.cc:1458
#5  0x000014b4aa9c72eb in CALL_2ARGS (a2=<optimized out>, a1=<optimized out>, f=<optimized out>) at src/calls.h:316
#6  EvalOrExecCall (opts=0, call=288, nr=2, ignoreResult=0) at src/funcs.c:150
#7  EvalFunccall2args (call=288) at src/funcs.c:322
#8  0x000014b4aaa70f18 in EVAL_EXPR (expr=<optimized out>) at src/exprs.h:98
#9  ExecAssLVar (stat=<optimized out>) at src/vars.c:167
#10 0x000014b4aaa4d5ce in EXEC_STAT (stat=<optimized out>) at src/stats.c:53
#11 ExecSeqStatHelper (nr=6, stat=<optimized out>) at src/stats.c:148
#12 ExecSeqStat6 (stat=<optimized out>) at src/stats.c:187
#13 0x000014b4aaa4fa8d in EXEC_STAT (stat=40) at src/stats.c:53
#14 EXEC_CURR_FUNC () at src/stats.c:59
#15 0x000014b4aa9c878d in DoExecFunc (arg=<synthetic pointer>, narg=2, func=0x14b4cfa5b2c0) at src/funcs.c:482
#16 DoExecFunc2args (func=0x14b4cfa5b2c0, a1=0x14b450020090, a2=0x14b450020230) at src/funcs.c:509
#17 0x000014b4aaa10d38 in CALL_2ARGS (a2=0x14b450020230, a1=0x14b450020090, f=<optimized out>) at src/calls.h:316
#18 CallNArgs<2> (a3=0x0, a4=0x0, a5=0x0, a6=0x0, a2=0x14b450020230, a1=0x14b450020090, method=<optimized out>) at src/opers.cc:1827
#19 DoOperationNArgs<2, 0, 0> (a3=0x0, a4=0x0, a5=0x0, a6=0x0, a2=0x14b450020230, a1=0x14b450020090, oper=0x14b4cd43a9a0) at src/opers.cc:1984
#20 DoOperation2Args (oper=0x14b4cd43a9a0, a1=0x14b450020090, a2=0x14b450020230) at src/opers.cc:2003
#21 0x000014b4aa98f9c6 in ProdObject (opL=<optimized out>, opR=<optimized out>) at src/ariths.c:905
#22 0x000014b4aaa70f18 in EVAL_EXPR (expr=<optimized out>) at src/exprs.h:98
#23 ExecAssLVar (stat=<optimized out>) at src/vars.c:167
#24 0x000014b4aaa4d73e in EXEC_STAT (stat=<optimized out>) at src/stats.c:53
#25 ExecSeqStatHelper (nr=4, stat=<optimized out>) at src/stats.c:148
#26 ExecSeqStat4 (stat=<optimized out>) at src/stats.c:177
#27 0x000014b4aaa4fa8d in EXEC_STAT (stat=40) at src/stats.c:53
#28 EXEC_CURR_FUNC () at src/stats.c:59
#29 0x000014b4aa9c878d in DoExecFunc (arg=<synthetic pointer>, narg=2, func=0x14b4cf754410) at src/funcs.c:482
#30 DoExecFunc2args (func=0x14b4cf754410, a1=0x14b450020140, a2=0x14b450020280) at src/funcs.c:509
...
```

And interrupting the test process gave the following exception which might give a hint which test is triggering this:
```julia
ERROR: LoadError: LoadError: LoadError: InterruptException:
Stacktrace:
  [1] _call_gap_func(func::GAP.GapObj, a1::GAP.GapObj, a2::GAP.GapObj)
    @ GAP /home/datastore/lorenz/software/julia/depot/packages/GAP/3WJE7/src/ccalls.jl:270
  [2] call_gap_func_nokw
    @ /home/datastore/lorenz/software/julia/depot/packages/GAP/3WJE7/src/ccalls.jl:224 [inlined]
  [3] (::GAP.GapObj)(a1::GAP.GapObj, a2::GAP.GapObj)
    @ GAP /home/datastore/lorenz/software/julia/depot/packages/GAP/3WJE7/src/ccalls.jl:235
  [4] isisomorphic(G::FPGroup, H::PermGroup)
    @ Oscar /home/datastore/lorenz/software/julia/Oscar.jl/src/Groups/homomorphisms.jl:318
  [5] macro expansion
    @ /home/datastore/lorenz/software/julia/Oscar.jl/test/Groups/libraries.jl:46 [inlined]
  [6] macro expansion
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
  [7] top-level scope
    @ /home/datastore/lorenz/software/julia/Oscar.jl/test/Groups/libraries.jl:38
  [8] include(fname::String)
    @ Base.MainInclude ./client.jl:444
  [9] top-level scope
    @ /home/datastore/lorenz/software/julia/Oscar.jl/test/Groups/runtests.jl:12
 [10] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [11] top-level scope
    @ /home/datastore/lorenz/software/julia/Oscar.jl/test/runtests.jl:20
 [12] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [13] top-level scope
    @ none:6
in expression starting at /home/datastore/lorenz/software/julia/Oscar.jl/test/Groups/libraries.jl:37
in expression starting at /home/datastore/lorenz/software/julia/Oscar.jl/test/Groups/runtests.jl:12
in expression starting at /home/datastore/lorenz/software/julia/Oscar.jl/test/runtests.jl:20
```

Downgrading to GAP 0.7.0 seems to fix it, with the following versions:
```
(Oscar) pkg> add GAP@v0.7.0
   Resolving package versions...
    Updating `/home/datastore/lorenz/software/julia/Oscar.jl/Project.toml`
  [c863536a] ↓ GAP v0.7.1 ⇒ v0.7.0
    Updating `/home/datastore/lorenz/software/julia/Oscar.jl/Manifest.toml`
  [c863536a] ↓ GAP v0.7.1 ⇒ v0.7.0
  [5cd7a574] ↓ GAP_jll v400.1191.1+0 ⇒ v400.1190.205+0
  [de1ad85e] ↓ GAP_lib_jll v400.1191.0+0 ⇒ v400.1190.200+0
```

**Comment by fingolfin** [comment]
I have an idea what the cause is but need to feed the monsters, err, kids

**Comment by lkastner** [comment]
Can we maybe change the workflows such that master breaks less often?

**Comment by fingolfin** [comment]
@lkastner I don't think master breaks "often" at all? The only recent breakage I recall was due to an "obviously harmless" change being committed directly to master -- the fix there is clear, always use PRs.

The other source is when two PRs are merged in row which both pass tests, but together they fail. This is currently hard to detect, although the [Pull Request Merge Queue](https://github.blog/changelog/2021-10-27-pull-request-merge-queue-limited-beta/) would help (I already registered us for the limited beta)


But it will always be possible for an external change to break Oscar, as was the case here.

**Comment by lkastner** [comment]
@fingolfin I did not say that master breaks often, I just want it to break less often, i.e. in those cases which we can prevent with reasonable effort without killing development. So why not only allow the CI to merge to master? And only allow PRs to merge whose tests pass, maybe excluding nightly?

You are right that external changes can and will break Oscar, which should motivate us even more to prevent the things that we can prevent. Also I would classify this case as preventable.
